# Datasource PostgreSQL (Lê variáveis de ambiente na nuvem / Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/sifinap}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sifinap}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sifinap123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Servidor (Render define a variável PORT automaticamente)
server.port=${PORT:8080}

# Logging
logging.level.com.sifinap=DEBUG
